export const articles={
ko:[
{slug:"exam-overview",category:"시험 구조",title:"전기기사 시험 구조를 한 장에 정리하기",description:"필기 5과목과 실기 필답형의 시간, 문항, 합격 기준을 먼저 고정합니다.",sections:[["필기는 5과목 100문항","전기자기학, 전력공학, 전기기기, 회로이론 및 제어공학, 전기설비기술기준을 과목당 20문항씩 풉니다."],["과목당 30분의 리듬","총 150분이지만 한 과목에 시간을 몰아 쓰면 뒤 과목에서 과락 위험이 커집니다. 과목별 검토 시간을 따로 정하세요."],["실기는 150분 필답형","전기설비설계 및 관리에서 계산 과정, 식, 단위와 판단 근거를 글로 남기는 연습이 필요합니다."],["합격선은 두 겹입니다","필기는 모든 과목 40점 이상과 전 과목 평균 60점 이상을 모두 만족해야 하며, 실기는 60점 이상입니다."]]},
{slug:"five-subject-map",category:"필기 전략",title:"필기 5과목을 하나의 연결 지도로 공부하기",description:"과목별 암기를 넘어 같은 전기 개념이 어디서 다시 등장하는지 연결합니다.",sections:[["전기자기학이 바닥을 만듭니다","전계, 자계, 유도와 에너지는 전기기기와 회로 문제를 해석하는 언어가 됩니다."],["회로이론은 계산 도구입니다","복소수, 임피던스, 과도현상과 제어의 기본은 전력공학과 실기 계산으로 이어집니다."],["전력과 기기를 양방향으로 연결합니다","발전·송전·배전의 계통 관점과 변압기·회전기의 장치 관점을 같은 회로 위에서 비교하세요."],["기술기준은 마지막 과목이 아닙니다","KEC와 전기설비기술기준의 수치·보호 원칙을 계산 문제의 실제 설계 조건과 함께 묶어야 오래 남습니다."]]},
{slug:"electromagnetics",category:"전기자기학",title:"전기자기학 공식을 방향과 단위로 기억하기",description:"기호 암기 대신 장, 힘, 에너지의 관계와 단위 검산으로 문제를 풉니다.",sections:[["공식마다 물리량을 말로 풉니다","식에 값을 넣기 전에 무엇이 원인이고 무엇이 결과인지 한 문장으로 설명하면 잘못된 공식을 고르기 어렵습니다."],["벡터 방향을 먼저 그립니다","전계·자계·힘의 방향은 부호보다 그림이 빠릅니다. 오른손 법칙과 경계 조건을 작은 스케치로 남기세요."],["단위가 오답을 잡아냅니다","계산 뒤 V/m, T, Wb, H 같은 단위를 확인하면 지수와 길이·면적 환산 실수를 찾을 수 있습니다."],["유사 공식을 한 표에서 비교합니다","정전계와 정자계, 직렬과 병렬, 에너지와 힘처럼 혼동되는 식을 조건·기호·단위로 나란히 정리하세요."]]},
{slug:"power-systems",category:"전력공학",title:"송배전 문제를 계통 흐름으로 해석하기",description:"발전기에서 부하까지의 흐름을 따라 전압, 손실, 고장을 정리합니다.",sections:[["단선도를 먼저 읽습니다","전원, 변압기, 선로, 차단기와 부하의 위치를 확인한 뒤 기준 전압과 전력 방향을 표시하세요."],["퍼센트와 실제값을 분리합니다","단위법과 퍼센트 임피던스를 섞지 말고 기준용량·기준전압을 먼저 고정해야 환산 오류가 줄어듭니다."],["고장 계산은 가정에서 시작합니다","3상 단락, 지락 등 고장 종류에 따라 사용하는 회로와 대칭분이 달라집니다. 문제의 고장 조건을 첫 줄에 쓰세요."],["경제성과 안정도를 함께 봅니다","역률 개선, 전압강하, 손실, 조상설비 문제는 단순 계산뿐 아니라 왜 그 조치가 필요한지까지 이해해야 응용에 강해집니다."]]},
{slug:"machines",category:"전기기기",title:"변압기와 회전기를 등가회로로 묶기",description:"기기별 구조를 외우기 전에 입력·손실·출력의 공통 골격을 잡습니다.",sections:[["에너지 변환 경로를 그립니다","입력에서 동손·철손·기계손을 거쳐 출력으로 가는 흐름을 그리면 효율과 손실 문제가 단순해집니다."],["등가회로의 각 항을 설명합니다","저항, 리액턴스, 여자분이 실제 기기의 어떤 현상을 나타내는지 연결하세요."],["속도와 주파수 관계를 고정합니다","동기속도, 슬립, 극수와 주파수의 관계는 유도기와 동기기 문제의 출발점입니다."],["특성곡선은 운전 상황으로 읽습니다","무부하·부하, 여자 변화, 토크 변화가 전압·전류·속도에 어떤 영향을 주는지 방향부터 판단하세요."]]},
{slug:"circuits-control",category:"회로·제어",title:"회로이론과 제어공학 계산 순서 만들기",description:"복소수 회로와 블록선도를 일정한 절차로 풀어 계산 누락을 줄입니다.",sections:[["회로의 상태를 먼저 분류합니다","직류·교류, 정상상태·과도상태, 대칭·비대칭을 구분해야 사용할 법칙과 표현이 정해집니다."],["복소수 표현을 끝까지 통일합니다","직교형과 극형을 오갈 때 각도 단위와 부호를 확인하고 중간에 실수값만 취하지 마세요."],["블록선도는 경로별로 줄입니다","직렬, 병렬, 피드백을 한 번에 처리하지 말고 안쪽 루프부터 단계별로 등가화하세요."],["결과의 방향을 검산합니다","저항 증가, 이득 변화, 감쇠 변화가 결과를 키워야 하는지 줄여야 하는지 물리적으로 확인하세요."]]},
{slug:"standards-kec",category:"기술기준",title:"KEC와 전기설비기술기준을 최신 기준으로 공부하기",description:"고시 기준일과 적용 조건을 확인하고 숫자만 분리 암기하지 않습니다.",sections:[["시험일 기준 최신 규정을 확인합니다","Q-Net은 전기설비기술기준과 KEC를 시험일 전에 최근 고시된 기준으로 준비하라고 안내합니다."],["수치는 조건과 함께 적습니다","전압 구분, 시설 장소, 보호 방식 같은 전제가 다르면 같은 설비도 요구값이 달라질 수 있습니다."],["보호 목적을 먼저 이해합니다","감전, 과전류, 지락, 열과 화재 위험 중 무엇을 막는 규정인지 알면 예외 조건을 구분하기 쉽습니다."],["오래된 요약본을 경계합니다","법령·고시가 바뀔 수 있으므로 개인 노트와 문제 해설의 기준일을 표시하고 Q-Net 출제기준과 최신 고시를 대조하세요."]]},
{slug:"practical-written-response",category:"실기",title:"150분 필답형 답안을 끝까지 완성하는 법",description:"계산식, 근거, 단위와 최종 답을 채점 가능한 형태로 남깁니다.",sections:[["문제 요구를 동사로 표시합니다","계산, 선정, 설명, 작성 중 무엇을 요구하는지 표시하면 필요한 답안 형식이 분명해집니다."],["식과 대입을 분리합니다","사용한 일반식, 수치 대입, 계산 결과를 순서대로 적으면 부분점수 가능성과 검산성이 높아집니다."],["단위와 반올림을 통일합니다","중간 계산은 충분한 자릿수를 유지하고 최종 답에서 요구 단위로 변환한 뒤 반올림하세요."],["막힌 문제는 공간을 남기고 이동합니다","150분을 한 문제에 소모하지 말고, 먼저 풀 수 있는 문항을 완성한 뒤 표시한 문제로 돌아오세요."]]},
{slug:"eligibility-registration",category:"응시 준비",title:"응시자격과 접수 일정을 안전하게 확인하기",description:"학력·자격·경력 경로는 Q-Net 자가진단과 서류심사로 확정합니다.",sections:[["응시자격은 개인별로 다릅니다","관련학과 학력, 산업기사·기능사와 경력, 동일·유사 직무 경력 등 여러 경로가 있어 단순 표만으로 확정하면 안 됩니다."],["자가진단 뒤 서류를 준비합니다","Q-Net 응시자격 자가진단은 출발점이며, 최종 인정은 지정 기간 안의 서류심사 결과를 따릅니다."],["회차별 기준일을 확인합니다","졸업예정, 경력 산정과 서류 제출 가능 기간은 회차별 일정과 심사 기준일에 맞춰 확인하세요."],["필기 합격 면제기간을 관리합니다","필기 합격자는 발표일로부터 2년간 필기시험이 면제됩니다. 실기 계획을 세울 때 정확한 발표일과 회차를 기록하세요."]]},
{slug:"eight-week-plan",category:"학습 계획",title:"8주 필기·실기 연결 학습 계획",description:"다섯 과목의 과락을 막으면서 필답형 표현을 매주 함께 연습합니다.",sections:[["1~2주는 기반을 통일합니다","전기자기학과 회로이론의 핵심 물리량, 복소수, 단위와 공식을 정리하고 짧은 계산을 매일 풉니다."],["3~5주는 과목을 연결합니다","전력공학·전기기기를 중심으로 계통과 장치의 관계를 익히고 기술기준을 같은 주제의 조건으로 붙입니다."],["6~7주는 100문항 리듬을 만듭니다","150분 모의고사를 치른 뒤 과목별 점수, 시간, 실수 유형을 기록해 과락 위험 과목을 먼저 보완합니다."],["8주는 필답형을 완성합니다","계산식·단위·서술을 갖춘 답안을 제한 시간에 작성하고, 최신 출제기준과 KEC 확인 목록을 마지막으로 점검합니다."]]}
],
en:[
{slug:"exam-overview",category:"Format",title:"The Korean Electrical Engineer exam at a glance",description:"Fix the written and practical structure before choosing a study plan.",sections:[["The written stage has 100 items","Five subjects each contribute 20 multiple-choice items."],["Each subject has 30 minutes","The total is 150 minutes, but subject-level pacing matters because every subject has a score floor."],["The practical is a 150-minute written response","Electrical Facility Design and Management requires calculations, units and reasoned written answers."],["Two written conditions apply","Pass every written subject at 40 or above and achieve at least 60 overall; the practical pass mark is 60."]]},
{slug:"five-subject-map",category:"Written strategy",title:"Map five subjects as one electrical system",description:"Connect recurring concepts instead of memorising five isolated books.",sections:[["Electromagnetics supplies the language","Fields, induction and energy recur in machines and circuit interpretation."],["Circuit theory supplies the tools","Impedance, transients and control fundamentals carry into power systems and practical calculations."],["Link systems and machines","Study the grid view of generation, transmission and distribution alongside the device view of transformers and rotating machines."],["Treat standards as design constraints","KEC and technical standards belong beside calculations, not in a disconnected final chapter."]]},
{slug:"electromagnetics",category:"Electromagnetics",title:"Remember formulas through direction and units",description:"Use physical meaning and dimensional checks instead of symbol-only recall.",sections:[["Say what the formula describes","Name the cause and result before substituting numbers."],["Sketch vector direction","A small field or force sketch is faster and safer than guessing a sign."],["Let units catch errors","Check V/m, T, Wb, H and length or area conversions after every result."],["Compare lookalike formulas","Place electric and magnetic cases side by side with conditions, symbols and units."]]},
{slug:"power-systems",category:"Power systems",title:"Read transmission problems as system flow",description:"Follow energy from source to load to organise voltage, loss and fault calculations.",sections:[["Start from the one-line diagram","Mark sources, transformers, lines, breakers, loads, base voltage and power direction."],["Separate per-unit and actual values","Fix base power and voltage before conversion."],["State the fault assumption","The network and sequence model depend on whether the fault is three-phase, line-to-ground or another type."],["Connect economy and stability","Power factor, voltage drop, loss and compensation questions test the reason for an action as well as arithmetic."]]},
{slug:"machines",category:"Machines",title:"Unify transformers and rotating machines",description:"Use equivalent circuits and energy flow as a shared frame.",sections:[["Draw the conversion path","Track input through copper, iron and mechanical losses to output."],["Explain every circuit term","Link resistance, reactance and excitation branches to physical behaviour."],["Fix speed and frequency relations","Synchronous speed, slip, poles and frequency form the starting point for induction and synchronous machines."],["Read curves as operating stories","Predict how voltage, current, speed and torque respond before calculating exact values."]]},
{slug:"circuits-control",category:"Circuits and control",title:"Use repeatable steps for circuits and control",description:"Standardise complex-number and block-diagram work to reduce omissions.",sections:[["Classify the state first","Identify DC or AC, steady or transient, balanced or unbalanced."],["Keep complex notation consistent","When moving between rectangular and polar forms, check angle units and signs."],["Reduce block diagrams from inside out","Handle series, parallel and feedback groups one stage at a time."],["Check the physical direction","Ask whether more resistance, gain or damping should increase or decrease the result."]]},
{slug:"standards-kec",category:"Standards",title:"Study KEC against the current effective rules",description:"Keep numeric requirements attached to their conditions and effective dates.",sections:[["Check the rule in force on the exam date","Q-Net instructs candidates to use the most recently announced technical and KEC rules before the test."],["Write numbers with conditions","Voltage class, location and protection method can change the required value."],["Understand the protection purpose","Identify whether the rule addresses shock, overcurrent, earth fault, heat or fire."],["Date every summary","Older notes can become stale, so reconcile them with the Q-Net specification and current official notices."]]},
{slug:"practical-written-response",category:"Practical",title:"Complete a scorable 150-minute written response",description:"Show equations, reasoning, units and the final answer clearly.",sections:[["Mark the command verb","Calculate, select, explain and draw require different answer forms."],["Separate formula and substitution","Write the general equation, inserted values and result in order."],["Control units and rounding","Retain sufficient precision until the final requested unit."],["Move on with space reserved","Do not lose the full session to one blocked item; complete accessible marks and return."]]},
{slug:"eligibility-registration",category:"Registration",title:"Verify eligibility and registration safely",description:"Use Q-Net self-check and document review for an individual decision.",sections:[["Eligibility has several routes","Relevant education, prior certificates and experience can qualify through different paths."],["Self-check is only the start","Final recognition depends on Q-Net document review within the designated period."],["Check each session's reference dates","Expected graduation, experience and submission timing must align with the chosen exam session."],["Track the written-pass exemption","A written pass provides a two-year written-stage exemption from the announcement date."]]},
{slug:"eight-week-plan",category:"Study plan",title:"An eight-week written and practical plan",description:"Protect all five written subjects while practising written-response form every week.",sections:[["Weeks 1–2 build the base","Standardise quantities, complex numbers, units and core formulas in electromagnetics and circuits."],["Weeks 3–5 connect subjects","Link power systems and machines, adding standards as real design constraints."],["Weeks 6–7 build 100-item pacing","Run 150-minute mocks and log score, time and error type by subject."],["Week 8 completes practical responses","Write full calculations and explanations under time, then refresh the current specification and KEC checklist."]]}
]};
